### ISSUE TITLE
Use enaml-web as markup language

### ISSUE THREAD

**Issue by devxpy** [codelv/enaml-web#11]
THIS might sound a little annoying,

I'm trying to use it as a markup language, because i'm sick of writing HTML. 

I don't want to deal with the hassle of running python on web browser or using web-sockets to communicate with server.

I just want a better way to write UI than HTML

Related [SO](https://stackoverflow.com/questions/50366979/sass-like-thingy-but-for-html-a-k-a-html-for-humans) question

**Comment by frmdstryr** [comment]
Enaml is python so at some point it will need to be converted to html, whether served by a server or converted to a static site. 

With that said, I see nothing preventing you from creating enaml files for each page of a site like a markup language or reading enaml code from a db or something.
