### ISSUE TITLE
running multiple instances

### ISSUE THREAD

**Issue by vahndi** [codelv/enaml-web#12]
Hi @frmdstryr  could you give some comments on how to serve a site with a different instance of the model for each browser window? When I was testing enaml-web a couple of months ago, every new browser window would show the same view when changes were made in one view. Perhaps this is just my lack of understanding of tornado?

**Comment by frmdstryr** [comment]
Just construct a new View instance for each request, user,  or shared  document, etc.. For example  `View(model=get_model_for_request(request)).render()`. 

If you are using forms and http post you can reuse a shared view instance but pass in a new model based on the request's form data. `view.render(model=Model(**form))`. The render method now takes kwargs that it will call setattr on the view for each item. When reusing a shared view you also have to make sure you're using `<<` or `:=` operators so all the correct fields update.

Creating a new view is the easiest but reusing the view is faster as enaml only needs to update a subset of nodes. 

You can use cookies http://www.tornadoweb.org/en/stable/guide/security.html identify users and lookup their models.

**Comment by frmdstryr** [comment]
Please reopen if needed.
