### ISSUE TITLE
How to add dynamic JavaScript widget like Plot.ly?

### ISSUE THREAD

**Issue by kiwi0fruit** [codelv/enaml-web#16]
How to add existing dynamic JavaScript widget like Plot.ly?

Or if the JavaScript widget has some interface/API/signals that the app should react on then how to connect to them?

**Comment by kiwi0fruit** [comment]
By the way: what do you think about [Transcrypt](https://github.com/QQuick/Transcrypt)?

**Comment by frmdstryr** [comment]
Use it like you would with raw html.  Include plotly.js and add a small bootstrap js script to initialize the div.

To react to events you have to use websockets to send the event info to the server and add code to handle it.

**Comment by frmdstryr** [comment]
I added an example of this.
