### ISSUE TITLE
Meta tag property ?

### ISSUE THREAD

**Issue by olymk2** [codelv/enaml-web#18]
https://github.com/codelv/enaml-web/blob/e3a631ff4b45ca26949f05ca04c8bfa2e1d5189f/web/components/html.py#L456

Trying to add open graph data but I cant use property I assume it needs to be added to the above link ?

Or perhaps not as property does not appear to be a standard tag, so would I need to create a new element type ? and if so any docs on how to go about doing that ?

**Comment by frmdstryr** [comment]
You can add arbitrary xml attributes to any tag using `attrs = {'data-name': value, #etc...}` (see https://github.com/codelv/enaml-web/blob/master/web/components/html.py#L59), or you can always subclass a Tag  and add your own atom members.

**Comment by olymk2** [comment]
great that worked perfecty I just used attrs << {'key': 'value'} in the template file in the end
