### ISSUE TITLE
Plotly example: How to update the graph in an enaml-web way ?

### ISSUE THREAD

**Issue by youpsla** [codelv/enaml-web#23]
Do you think it's possible to replace a plotly graph with websocket by just modifyng the `traces` and `display` attribute of PlotlyGraph component ?
It doesn't works for me. Plotly.js doesn't seems to react when `data-traces` are modified in the DOM.

Any idea to do that without writing js for collecting all datas from Plotly div attribute and lauching a Plotly.react command ?

**Comment by frmdstryr** [comment]
Yes, this is currently done in one of my projects so the chart updates when the plot data changes. 

When a change occurs on one of the data-tags just rebuild the plot(s) using [Plotly.newPlot](https://plotly.com/javascript/plotlyjs-function-reference/#plotlynewplot).

**Comment by youpsla** [comment]
Thanks for your answer.
Then, if I understand well, I have to build a js function listening on data-tags change and launch a Plotly.NewPlot.

By the way I had to change `$tag.prop(k,v);` to `$tag.attr(k,v);` for the data-tag to be updated in the DOM.

Again thanks for your many, pleasure to use tools/frameworks.

**Comment by youpsla** [comment]
Let's go to work ... :-)
