### ISSUE TITLE
Adding observe event on a variable inside enaml file

### ISSUE THREAD

**Issue by youpsla** [codelv/enaml-web#24]
**Edit**: The above question solution will be useless in my case because I want an async function to be run when observed value change and I think I'll not able to call such a function inside enaml block.

-----------------------------------------------------------------
I would like to create a component with business logic embedded.

```
    Select: 
        self.observe('value', test)
        func test(self, change):
            pass
        Option:
            value = "0"
            text = "Zero"
        Option:
            value = "1"
            text = "One"
```
A syntax error is raised.

Any idea if it's possible ?

**Comment by frmdstryr** [comment]
Please read https://enaml.readthedocs.io/en/latest/get_started/syntax.html#binding-operators. In enaml you shouldn't have to use `observe`, instead just use a notification block.

```python
    Select: 
        func test(self, change):
            pass
        value :: test(change)
        Option:
            value = "0"
            text = "Zero"
        Option:
            value = "1"
            text = "One"
```

Next, all python (and enaml) operators are synchronous, so to run an async function you need to schedule it on the event loop. It depends on what event loop your using but something like [loop.call_soon](https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.loop.call_soon) from asyncio, or [IOLoop.call_later](https://www.tornadoweb.org/en/stable/ioloop.html#tornado.ioloop.IOLoop.call_later) for tornado, etc..

So something like

```python
    Select:  
        async func test(self, change):
            pass # Can now use async stuff here
        value :: IOLoop.current().call_later(test, change)
        Option:
            value = "0"
            text = "Zero"
        Option:
            value = "1"
            text = "One"
```

**Comment by youpsla** [comment]
Thanks a lots. I forgot the notification operator (My bad ....).

By the way, I tried to add the "Help wanted" label to my question but was not able to do so.

**Comment by youpsla** [comment]
I had to change the tornado call to the following one:
```
value :: IOLoop.current().call_later(0, method, change)
```

The first arg of call_later method has to be the delay: [call_later](https://github.com/tornadoweb/tornado/blob/b0f2479eadb23de5bed90f5f1cad0f159fa3602f/tornado/ioloop.py#L587)

Again, thanks for your detailed and very helpful answer and congrats for select_related in Atom-db.

**Comment by frmdstryr** [comment]
Ah, yeah sorry about that, was thinking of https://www.tornadoweb.org/en/stable/ioloop.html#tornado.ioloop.IOLoop.add_callback

**Comment by youpsla** [comment]
I decided to use add_callback as per the doc it is thread-safe.

**Comment by youpsla** [comment]
`add_callback` works well too. I'll use this because `Note that this is the only method in IOLoop that makes this thread-safety guarantee` as per the doc.
