### ISSUE TITLE
Launching a func when rendering component for the time and without end user action

### ISSUE THREAD

**Issue by youpsla** [codelv/enaml-web#25]
Hello,
I would like to launch a a func for collecting datas from the DB and assigning to component attribute at widget initialization.
Currently, I have this working by launching my function in my main.py file in the tornado RequestHandler. I would like to make my component containing the maximum code it use.
```
enamldef MyComponent(Html):
    attr datas

    async func get_datas_from_db(**parameters):
        return datas

    IOLoop.current().add_callback(get_datas_from_db, parameters) # Here is the syntax error

   Conditionnal:
        condition << datas is not None
       Looper:
            ...........

```

I haven't seen something like `on_prepare` which could be usefull ([prepare](https://github.com/codelv/enaml-web/blob/34096f5653990ab2a0bff0ef27d5003001e3657d/web/components/html.py#L215))

Any idea ?

Regards

**Comment by frmdstryr** [comment]
I typically just define an `async func get()` and invoke that from the request handler.

**Comment by youpsla** [comment]
Thanks for your answer. That's what I have done so far. Just wondering if there was a solution for putting the call inside the component.

**Comment by frmdstryr** [comment]
You can use the [activated](https://enaml.readthedocs.io/en/latest/api_ref/widgets/toolkit_object.html?highlight=activated#enaml.widgets.toolkit_object.ToolkitObject.activated) event to schedule an async function but that will not wait for the call to complete.
