### ISSUE TITLE
Enaml-web and Django

### ISSUE THREAD

**Issue by youpsla** [codelv/enaml-web#27]
Hello,
I'll have to create a project. I'm hesitating using enaml-web with Django. Enaml-web is so fun !!

I have seen the question has already been asked  #8.
You have answered 
>Yes. You can create a LxmlApplication which has no server component and then render pages for any application (django, flask, etc..) or save them to a file to make a static site.

You talked about LxmlApplication. Haven't see any code relating to that in master.

Could you give me some hints and how to do this coupling ?

Regards

**Comment by youpsla** [comment]
Not enough clear. I'll reopen it later with better explained question(s).

**Comment by frmdstryr** [comment]
Using `view.render()` returns a string so you should be able to just use it like any other response in django.  

```python
import enaml
from django.http import HttpResponse

with enaml.imports():
   from views import IndexView

def index(request):
    view = IndexView(request=request)
    return HttpResponse(view.render())

```

**Comment by youpsla** [comment]
As usual, thanks a lots for your answer. I'll give it a try next week.

**Comment by danieljfarrell** [comment]
@youpsla just wondering if you have a Hello World example that uses Django and Enaml?

**Comment by youpsla** [comment]
Hello @danieljfarrell . haven't had time to do it (new job !!!). When I have spare time, will be my first task.....

**Comment by danieljfarrell** [comment]
That would be great!

**Comment by youpsla** [comment]
> ```python
> with enaml.imports():
>    from views import IndexView
> ```

Hi. It's a long time ....

Tried the solution in a docker container. Got an issue with
```
with enaml.imports():
   from views import IndexView
```

My `views`file is a file named `views.enaml`. It's not a python file.

It raise an import error. I triedd to deep in `EnamlImporter` but didn't understood enough.

Any idea ?

**Comment by youpsla** [comment]
Found the solution.
Just had to add a dot for relative import:
> ```python
> with enaml.imports():
>    from .views import IndexView
> ```
