### ISSUE TITLE
How to implement a file upload button?

### ISSUE THREAD

**Issue by danieljfarrell** [codelv/enaml-web#28]
I'm interested in a very simple page that just provided an upload button.

If this was desktop Enaml I guess I would follow these steps:
1. Window with a button
2. On button click open a FileDialog widget 
3. Get the local file path when the widget closes
4. Use Python's `file` to get the bytes and then "do stuff" with bytes.

Are there similar widgets in Enable-Web? How might you go about doing this?

**Comment by frmdstryr** [comment]
Use enaml-web to render a page with [a file input](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file) and implement a handler to save it on the server (eg https://github.com/tornadoweb/tornado/blob/master/demos/file_upload/file_receiver.py)

**Comment by danieljfarrell** [comment]
Really that easy! Thanks so much!
