### ISSUE TITLE
Multi-pages website: Best pattern

### ISSUE THREAD

**Issue by youpsla** [codelv/enaml-web#29]
Hello.

I'm trying to setup a muti-pages website (was websocket only before).

My Base page is structured like this:

```python
# index.enaml

enamldef Item(Div):
    attrs item_ref

enamldef Statistics(Div):
    attrs datas

enamldef Home(Div):
    attrs datas

enamldef Index(MaterializePage): index:

    Block:
        block = parent.header
       .........
    Block: main_content:
        block = parent.content
        Home:
            pass
```

```python
# main.py

class IndexHandler(RequestHandler):
    async def get(self):
        path = self.request.path
        page = path.split('/)[1]

        if page == 'home':
                datas = await Model_A().get_datas()
        if page == 'statistics':
                datas = await Model_B().get_datas()
        
        index = Index()
       #
       # Here, how to change the content of index.main_content with datas set to the choosed child datas attribute
       #    
        self.write(index.render())
```

I was wondering if there is a solution for changing the main_content child widget with specific attributes datas from python file. This file handle request.

Do you have any suggestion about other patterns to accomplish that ?

Regards

**Comment by frmdstryr** [comment]
If you want to change nodes within enaml use the [Conditional](https://enaml.readthedocs.io/en/latest/api_ref/core/conditional.html) or [Include](https://enaml.readthedocs.io/en/latest/api_ref/core/include.html?highlight=include#) nodes.

If you just want to route different urls to different views I would just create a separate handler & view for each using whatever web framework you have.

**Comment by frmdstryr** [comment]
You can also assign variables when calling render or creating the view "class", eg

```python
class IndexHandler(RequestHandler):
    async def get(self):
        data = await self.get_data() # Get data
        index = Index(data=data)
        self.write(index.render()) # Could also pass kwargs here too
```

**Comment by youpsla** [comment]
Thanks a lots. I'll try that.
