### ISSUE TITLE
Support for Python 3?

### ISSUE THREAD

**Issue by vahndi** [codelv/enaml-web#3]
I noticed that the examples all use ```cyclone```, which is Python2 only. Is it possible to use ```enaml-web``` with any Python3 web servers?

**Comment by frmdstryr** [comment]
I have not tried it with python 3. 

Perhaps the [tornado](https://github.com/codelv/enaml-web/blob/master/web/impl/tornado_app.py) or [twisted](https://github.com/codelv/enaml-web/blob/master/web/impl/twisted_app.py) servers work.

Feel free to make a PR to add python 3 support. I've been waiting for enaml to merge the pending python 3 changes.

**Comment by vahndi** [comment]
Ok thanks for the pointers - I'll try those out this week and put something together.

**Comment by vahndi** [comment]
[tornado](https://github.com/codelv/enaml-web/blob/master/web/impl/tornado_app.py) seems to work fine with Python 3.
