### ISSUE TITLE
Django integration 2: How to persist Atom object between user request

### ISSUE THREAD

**Issue by youpsla** [codelv/enaml-web#34]
Hello !!!
I'm trying to integrate Enaml-web and Django using the CACHE system used ind dataframe example here:https://github.com/codelv/enaml-web/blob/37752a0221d1b9734d063daedbf39a3d9b9f51e3/examples/dataframe_viewer/app.py#L48

I don't achieve to persist this object between users interactions, in other works, after the answer has been sent back to the user browser.

Any idea to achieve that ?

Here is my simple view:
```python

from django.http import HttpResponse

from web.core.app import WebApplication
import enaml

with enaml.imports():
    from .index import Index
enaml_web_app = WebApplication()



def testview(request):
    # I would like to cache index to be able to retrieve it later.
    index = Index()
    return HttpResponse(index.render())


```

**Comment by youpsla** [comment]
The solution I found as of now is to setup another server.
Then, one Django server and one "Enaml-redering-and-cache-server".
When Django receive a request, he send a request to the "Enamll" server and get the HTML (Partial or full page).

**Comment by frmdstryr** [comment]
Have you tried using [django's cache framework](https://docs.djangoproject.com/en/4.1/topics/cache/ ) to save the page? 

Or more simply some global variable outside the request handler? Something like this:

```python
CACHE = {}

def testview(request):
    cache_key = "index"
    data = CACHE.get(cache_key)
    if data is None:
        # page is not in cache, render it and save it in the cache
        print("Creating cache")
        index = Index()
        data = (index, index.render())
        CACHE[cache_key] = data 
    else:
        print("Using cache")
    index, page = data
    return HttpResponse(page)

```

A similar approach will work with the dataframe viewer example.

**Comment by youpsla** [comment]
I close this ticket because I solved the issue a long time ago and forgot it.
Thanks again for help.
