### ISSUE TITLE
error using tornado for data-binding demo

### ISSUE THREAD

**Issue by vahndi** [codelv/enaml-web#5]
Hi, I'm getting this error in the browser console when running the data binding demo using tornado. Any ideas where to start looking? Shall I check the javascript or do you think it's tornado?
```
VM47:164 WebSocket connection to 'ws://localhost:8888/' failed: Error during WebSocket handshake: Unexpected response code: 200
WrappedWebSocket @ VM47:164
```
Thanks

**Comment by frmdstryr** [comment]
My guess would be the 'is_websocket' method

**Comment by frmdstryr** [comment]
Sorry that's not the problem. I updated it in https://github.com/codelv/enaml-web/commit/5cbe1bcbd9d530cd1378deea76a11d472a88fe14 to work with tornado.

**Comment by vahndi** [comment]
thanks!
